name: 'RepoDynamics Context'
description: 'Add workflow contexts to GitHub Actions job summaries.'
author: 'Armin Ariamajd'
branding:
  icon: file-text
  color: blue


runs:
  using: "composite"
  steps:

    - name: 'Setup Python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 'Install dependencies'
      run: pip install repodynamics[context]
      shell: bash

    - name: "Run"
      env:
        RD__CONTEXT__GITHUB: ${{ toJson(github) }}
        RD__CONTEXT__JOB: ${{ toJson(job) }}
        RD__CONTEXT__STEPS: ${{ toJson(steps) }}
        RD__CONTEXT__RUNNER: ${{ toJson(runner) }}
        RD__CONTEXT__STRATEGY: ${{ toJson(strategy) }}
        RD__CONTEXT__MATRIX: ${{ toJson(matrix) }}
      run: python -m repodynamics.actions context
      shell: bash
