name: 'RepoDynamics Context'
description: 'Add workflow contexts to GitHub Actions job summaries.'
author: 'Armin Ariamajd'
branding:
  icon: file-text
  color: blue


runs:
  using: "composite"
  steps:

    - name: 'Logo'
      shell: bash
      run: |
        # Intro
        printf "\n\n$(cat ${{github.action_path}}/logo.txt)\n\n\n"
    

    - name: 'Setup Python'
      run: |
        # Setup Python
        H="\033[1;30;43m"  
        echo -e "\n${H} 1. Setting up Python \n"
      shell: bash
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'


    - name: 'Install Repodynamics'
      run: |
        # Install Repodynamics
        H="\033[1;30;43m" 
        echo -e "\n${H} 2. Installing Repodynamics \n"
      shell: bash
    - run: pip install repodynamics[context]
      shell: bash


    - name: "Run"
      run: |
        # Run
        H="\033[1;30;43m" 
        echo -e "\n${H} 3. Running Repodynamics Context \n"
      shell: bash
    - run: python -m repodynamics.actions context
      shell: bash
      env:
        RD__CONTEXT__GITHUB: ${{ toJson(github) }}
        RD__CONTEXT__JOB: ${{ toJson(job) }}
        RD__CONTEXT__STEPS: ${{ toJson(steps) }}
        RD__CONTEXT__RUNNER: ${{ toJson(runner) }}
        RD__CONTEXT__STRATEGY: ${{ toJson(strategy) }}
        RD__CONTEXT__MATRIX: ${{ toJson(matrix) }}
