name: 'RepoDynamics: Workflow Context'
author: 'Armin Ariamajd'
description: 'Add workflow contexts to your job summary.'
branding:
  icon: file-text
  color: blue


runs:
  using: "composite"
  steps:

    - run: echo ${{ github.action_path }}
      shell: bash

    - run: echo ${GITHUB_ACTION_PATH}
      shell: bash

    - run: ls /
      shell: bash

    - run: |
        cd ${GITHUB_ACTION_PATH}
        ls .
      shell: bash

    - run: |
        cd ${{ github.action_path }}
        ls .
      shell: bash






    - run: echo $GITHUB_ACTION_PATH
      shell: bash
#    - name: 'Checkout repository'
#      uses: actions/checkout@v3
#      with:
#        sparse-checkout: ${{ github.action_path }}
#        sparse-checkout-cone-mode: false

    - name: 'Setup Python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
#        cache-dependency-path: ${GITHUB_ACTION_PATH}/requirements.txt

    - name: 'Install dependencies'
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - run: echo "$PATH"
      shell: bash

#    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
#      shell: bash

    - run : echo "$PATH"
      shell: bash

    - run: find .
      shell: bash

    - name: "Run"
      # https://github.com/crazy-max/ghaction-dump-context/blob/master/action.yml
      env:
        RD__WORKFLOW_CONTEXT__GITHUB: ${{ toJson(github) }}
        RD_JOB_CONTEXT: ${{ toJson(job) }}
        RD_STEPS_CONTEXT: ${{ toJson(steps) }}
        RD_RUNNER_CONTEXT: ${{ toJson(runner) }}
        RD_STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        RD_MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: python "${{ github.action_path }}/src/workflow_context.py"
      shell: bash
