name: 'RepoDynamics: Workflow Context'
author: 'Armin Ariamajd'
description: 'Add workflow contexts to your job summary.'
branding:
  icon: file-text
  color: blue


runs:
  using: "composite"
  steps:

    - name: 'Setup Python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
        cache-dependency-path: requirements.txt

    - name: 'Install dependencies'
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - run: echo "$PATH"
      shell: bash

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - run : echo "$PATH"
      shell: bash

    - run: find .
      shell: bash

    - name: "Run"
      # https://github.com/crazy-max/ghaction-dump-context/blob/master/action.yml
      env:
        RD__WORKFLOW_CONTEXT__GITHUB: ${{ toJson(github) }}
        RD_JOB_CONTEXT: ${{ toJson(job) }}
        RD_STEPS_CONTEXT: ${{ toJson(steps) }}
        RD_RUNNER_CONTEXT: ${{ toJson(runner) }}
        RD_STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        RD_MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: python "${{ github.action_path }}/src/workflow_context.py"
      shell: bash
