name: 'RepoDynamics Context'
description: 'Add workflow contexts to GitHub Actions job summaries.'
author: 'Armin Ariamajd'
branding:
  icon: file-text
  color: blue


runs:
  using: "composite"
  steps:

    - name: 'Logo'
      shell: bash
      run: |
        # Intro
        printf "\n\n$(cat ${{github.action_path}}/logo.txt)\n\n\n"
    

    - name: 'Setup Python'
      run: |
        # Setup Python
        echo -e "\n\033[1;30;43m 1. Setting up Python "
      shell: bash
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'


    - name: 'Install Repodynamics'
      run: |
        # Install Repodynamics
        echo -e "\n\033[1;30;43m 2. Installing Repodynamics "
        pip install repodynamics[context]
      shell: bash


    - name: "Run"
      run: |
        # Run
        echo -e "\n\033[1;30;43m 3. Running Repodynamics Context "
        python -m repodynamics.actions context
      shell: bash
      env:
        RD__CONTEXT__GITHUB: ${{ toJson(github) }}
        RD__CONTEXT__JOB: ${{ toJson(job) }}
        RD__CONTEXT__STEPS: ${{ toJson(steps) }}
        RD__CONTEXT__RUNNER: ${{ toJson(runner) }}
        RD__CONTEXT__STRATEGY: ${{ toJson(strategy) }}
        RD__CONTEXT__MATRIX: ${{ toJson(matrix) }}
